accounts/urls.py
from django.urls import path
from .views import (
   RegistUserView,HomeView,
   UserLoginView, UserLogoutView,
   ProfileEditView,UserListView, # 追加
)
app_name = 'accounts'
urlpatterns = [
   path('home/', HomeView.as_view(), name='home'),
   path('regist/', RegistUserView.as_view(), name='regist'),
   path('login/', UserLoginView.as_view(), name='login'),
   path('logout/', UserLogoutView.as_view(), name='logout'),
   path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'), # 追加
   path('userlist/', UserListView.as_view(), name='userlist'), # 追加
]

microposts/urls.py
from django.urls import path
from .views import (
    PostCreateView, PostListView,  # 追加
    PostUpdateView, PostDeleteView, PostDetailView,
    MyPostsView  # 追加
)
from . import views
app_name = 'microposts'
urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('postlist/', PostListView.as_view(), name='postlist'),  # 追加
    path('postlist/<int:pk>', PostDetailView.as_view(),
         name='postdetail'),  # 追加
    path('postlist/<int:pk>',
         PostDetailView.as_view(), name='createcomment'),  # 追加
    path('update/<int:pk>', PostUpdateView.as_view(), name='update'),  # 追加
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),  # 追加
    path('myposts/', MyPostsView.as_view(), name='myposts'),  # 追加

]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings  # mediaを使うために追加

urlpatterns = [
   path('admin/', admin.site.urls),
   path('accounts/', include('accounts.urls')), # 追加
   path('microposts/', include('microposts.urls')), # 追加
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microposts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Post(models.Model):
    # Postのオーナーを設定する
    owner = models.ForeignKey(
        'accounts.User', verbose_name='オーナー', on_delete=models.CASCADE)
    content = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'posts'


class Message(models.Model):
    id = models.BigAutoField(primary_key=True,)
    user_name = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.PROTECT,)
    comment = models.TextField(verbose_name='コメント')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post_id)


class Favorite(models.Model):
    user_name = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.PROTECT,)
    created_at = models.DateTimeField(auto_now_add=True)

microposts/forms.py
from xml.etree.ElementTree import Comment
from django import forms
from .models import Post, Message


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30,
                       'placeholder': 'ここに入力してください'}
            ),
        }


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30}
            ),
        }


class MessageCreateForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = (
            'comment',
        )
        widgets = {
            'comment': forms.Textarea(
                attrs={'rows': 1, 'cols': 30,
                       'placeholder': 'ここに入力してください'}
            ),
        }

microposts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Favorite, Post, Message
from .forms import PostCreateForm, PostUpdateForm, MessageCreateForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import TemplateView

# Create your views here.


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'microposts/create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('microposts:create')

    def form_valid(self, form):
        # formに問題なければ、owner id に自分のUser idを割り当てる
        # request.userが一つのセットでAuthenticationMiddlewareでセットされている。
        form.instance.owner_id = self.request.user.id
        messages.success(self.request, '投稿が完了しました')
        return super(PostCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '投稿が失敗しました')
        return redirect('microposts:create')


class PostListView(LoginRequiredMixin, ListView):
    # テンプレートを指定
    template_name = 'microposts/postlist.html'
    # 利用するモデルを指定
    model = Post
    # ページネーションの表示件数
    paginate_by = 10
    # Postsテーブルの全データを取得するメソッド定義
    # テンプレートでは、object_listとしてreturnの値が渡される

    def get_queryset(self):
        return Post.objects.all()


class PostDetailView(LoginRequiredMixin, TemplateView):
    # テンプレートを指定
    template_name = 'microposts/postdetail.html'
    form_class = MessageCreateForm

    def get_context_data(self, **kwargs):

        try:
            comments = Message.objects.filter(post_id=self.kwargs['pk'])
        except:
            comments = []
        try:
            favorites = Favorite.objects.filter(post_id=self.kwargs['pk'])
        except:
            favorites = []
        try:
            favorites_owner = Favorite.objects.filter(post_id=self.kwargs['pk'], user_name = self.request.user)
        except:
            favorites_owner = []
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        context['owner'] = post.owner
        context['post'] = post
        context['form'] = self.form_class
        context['comments'] = comments
        context['favorites'] = favorites
        context['favorites_owner'] = False
        for fa in favorites_owner:
            if fa.user_name.username == self.request.user.username:
                context['favorites_owner'] = True
        context['authenticated'] = self.request.user.is_authenticated

        return context

    def post(self, request, pk):
        form = MessageCreateForm(request.POST or None)
        if "favorite" in request.POST:
            favorite_list = Favorite.objects.filter(post_id=self.kwargs['pk'], user_name_id=request.user.id )
            if not favorite_list :
                print("list is empty")
                Favorite.objects.create(
                    post_id_id=pk, user_name_id=request.user.id )
            else :
                print("list is not empty")            
                favorite_list.delete()
                
        else:
            Message.objects.create(
                post_id_id=pk, user_name_id=request.user.id, comment=form.data['comment'])

        return redirect('microposts:postdetail', pk)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'microposts/update.html'

    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super(PostUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('microposts:update', kwargs={'pk': self.object.id})

    def form_invalid(self, form):
        messages.warning(self.request, '更新が失敗しました')
        return reverse_lazy('microposts:update', kwargs={'pk': self.object.id})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'microposts/delete.html'
    # deleteviewでは、SuccessMessageMixinが使われないので設定する必要あり
    success_url = reverse_lazy('microposts:create')
    success_message = "投稿は削除されました。"
    # 削除された際にメッセージが表示されるようにする。

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


class MyPostsView(LoginRequiredMixin, ListView):  # 追加
    # テンプレートを指定
    template_name = 'microposts/myposts.html'
    # 利用するモデルを指定
    model = Post
    # ページネーションの表示件数
    paginate_by = 10

    # Postsテーブルのowner_idが自分自身の全データを取得するメソッド定義
    def get_queryset(self):  # 自分の投稿オブジェクトを返す。
        return Post.objects.filter(owner_id=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Postsテーブルの自分の投稿数をmy_posts_countへ格納
        context['my_posts_count'] = Post.objects.filter(
            owner_id=self.request.user).count()
        return context

templates/microposts/create.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {# views.pyからmessagesが渡された場合にのみメッセージを表示させる。#}
                {% if messages %}
                {% for message in messages %}
                {# message/tagsはSettings.pyで設定している#}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
                {% endif %}
                <div class="card">
                    <div class="card-header">
                        <h4><b>新規投稿</b></h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button type="submit" class="btn btn-outline-primary btn-block">
                                投稿する
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/microposts/delete.html
{% extends 'base.html' %}
{% block content %}
{#    投稿したユーザーしか削除できない制約を追加#}
   {% if object.owner_id == user.id %}
       <form method="POST">
       {% csrf_token %}
       <p>「{{ object.content }}」を削除しますか？</p>
       <button type="submit" class="btn btn-default btn-danger">
           削除する
       </button>
   </form>
       {% else %}
       <h1>{{ user.get_username }}さんの投稿ではありません。</h1>
   {% endif %}
{% endblock %}

templates/microposts/myposts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <!--ページタイトル-->
            <aside class="col-sm-4">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title text-center">{{ user.get_username }}</h3>
                    </div>
                    <div class="card-body">
                        {# ユーザーがプロフィール画像を持っている場合#}
                        {% if user.avatar %}
                        <img class="rounded img-fluid mx-auto d-block" src="{{ user.avatar.url }}" id="avatar-image"
                            alt="avatar_image">
                        {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                        {% else %}
                        <img class="rounded img-fluid mx-auto d-block" src="/media/upper_body-2.png"
                            alt="avatar_thumbnail" id="avatar-thumbnail">
                        {% endif %}
                    </div>
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'accounts:edit_profile' %}"
                        role="button">プロフィール更新</a>
                </div>
            </aside>
            <div class="col-sm-8">
                <ul class="nav nav-tabs nav-justified mb-3">
                    <li class="nav-item"><a href="{% url 'microposts:myposts' %}" class="nav-link active">MyPosts一覧
                            {# object_listのlengthを取得することで投稿数をカウントできる。#}
                            <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Followings
                            {# フォロワー数を表示#}
                            <span class="badge badge-secondary">"#"</span></a></li>
                    <li class="nav-item"><a href="#" class="nav-link">Followers
                            {# フォロワー数を表示#}
                            <span class="badge badge-secondary">"#"</span></a></li>
                </ul>
                <!-- テーブル表の定義 -->
                <div class="table table-responsive">
                    <table id='post_list' class="table table-striped table-bordered table-hover">
                        　
                        <!-- 表の列の定義-->
                        <thead>
                            <tr>
                                <th class="text-center" style="width: 80%">投稿内容</th>
                                <th class="text-center" style="width: 20%">更新／削除</th>
                            </tr>
                        </thead>
                        　
                        <!-- ここまでが表の列の定義-->
                        　
                        <!-- 表のデータ部分の表示-->
                        <tbody>
                            {% for item in object_list %}
                            <tr class="text">
                                <td class="text">
                                    <h6>@{{ item.created_at }}</h6>
                                    <a href="{% url 'microposts:postdetail' pk=item.pk %}">{{ item.content }}</a>
                                </td>
                                <td class="text-center align-middle">
                                    {# pkを指定する際は、urlタグはやや特殊な書き方となる↓以下参照#}
                                    <a class="btn btn-outline-success btn-sm"
                                        href="{% url 'microposts:update' item.pk %}" role="button">更新</a>
                                    <a class="btn btn-outline-danger btn-sm"
                                        href="{% url 'microposts:delete' item.pk %}" role="button">削除</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        　
                        <!-- ここまでが表のデータ部分の表示-->
                    </table>
                    <!-- ここまでがテーブル表の定義 -->
                </div>
                {# django-bootstrap4のページネーション#}
                {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/microposts/postdetail.html
{% extends 'base.html' %}
{% block content %}

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                <div class="card">
                    <div class="card-header">
                        <h4><b>投稿内容</b></h4>
                    </div>
                    <div class="detail card-body">
                        {% csrf_token %}
                        <div class="detail_row">
                            {% if owner.avatar %}
                            <img class="detail_icon col rounded img-fluid mx-auto d-block" src="{{ owner.avatar.url }}"
                                id="avatar-image" alt="avatar_image">
                            {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                            {% else %}
                            <img class="detail_icon col rounded img-fluid mx-auto d-block" src='/media/upper_body-2.png'
                                id="avatar-image" alt="avatar_image">
                            {% endif %}
                            <div class="row detail_username">@{{ owner.username }}</div>
                        </div>
                    </div>
                    <!-- {{ user }} /
                    {{ favorites.0.user_name }} -->
                    <div class="row detail_content">{{ post.content }}</div>
                    <div class="row reply_items">
                        <button id="comment-dots" class="button is-success" value="favorite" name="favorite">
                            <i class="fa-regular fa-comment-dots"></i>
                        </button>
                        <div class="comment_count"> {{ comments|length }}</div>
                        <form class="row" action="{% url 'microposts:postdetail' pk=post.pk %}" method="post">
                            {% csrf_token %}
                            <button id="comment-heart" class="button is-success" value="favorite" name="favorite">
                                {% if favorites_owner == True %}
                                    <i class="fa-solid fa-heart" style="color: red;"></i>
                                {% else %}
                                    <i class="fa-regular fa-heart"></i>
                                {% endif %}
                            </button>
                            <div class="favorite_count"> {{ favorites|length }}</div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% for comment in comments %}
        <div class="comment_list">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    <div class="comment_user_name">
                        @{{ comment.user_name }}
                    </div>
                    <div class="comment_user_name">
                        {{ comment.comment }}
                    </div>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
    <div class="post_comment row">
        <div class="col-sm-6 offset-sm-3">
            <form action="{% url 'microposts:postdetail' pk=post.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-outline-primary btn-block">
                    投稿する
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/microposts/postlist.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                <!--ページタイトル-->
                <div class="card mb-3">
                    <div class="card-header">
                        <h4><b>投稿一覧</b></h4>
                    </div>
                    <div class="card-body">
                        <!-- テーブル表の定義 -->
                        <div class="table table-responsive">
                            <table id='post_list' width="100%" class="table table-striped table-bordered table-hover">
                                <!-- 表の列の定義-->
                                <thead>
                                    <tr>
                                        <th class="text-center">投稿内容</th>
                                        <th class="text-center">お気に入り</th>
                                    </tr>
                                </thead>
                                <!-- ここまでが表の列の定義-->
                                <!-- 表のデータ部分の表示-->
                                <tbody>
                                    {# デフォルトはobject_listとなるが、view.pyでcontextとして指定することも出来る#}
                                    {% if object_list != 0 %}
                                    {% for item in object_list %}
                                    <tr class="text">
                                        <td class="text" style="width: 80%">
                                            <h6>{{ item.owner }}@{{ item.created_at}}</h6>
                                            <a href="{% url 'microposts:postdetail' pk=item.pk %}">{{ item.content }}</a>
                                        </td>
                                        <td class="text-center align-middle" style="width: 20%">
                                            ・・省略・・
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% endif %}
                                </tbody>
                                <!-- ここまでが表のデータ部分の表示-->
                            </table>
                            <!-- ここまでがテーブル表の定義 -->
                        </div>
                        {# django-bootstrap4のページネーション#}
                        {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/microposts/update.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {# views.pyからmessagesが渡された場合にのみメッセージを表示させる。#}
                {% if messages %}
                {% for message in messages %}
                {# message/tagsはSettings.pyで設定している#}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                    </li>
                    {% endfor %}
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <h4><b>投稿の更新</b></h4>
                        </div>
                        {# 投稿したユーザーしか削除できない制約を追加#}
                        {% if object.owner_id == user.id %}
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-outline-success btn-block">
                                    更新する
                                </button>
                            </form>
                            {% else %}
                            <p class='font-weight-bold text-danger text-center'>
                                {{ user.get_username }}さんの投稿ではありません。
                            </p>
                            {% endif %}
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}